title: Jim Boyle
author: Jim Boyle
email: boylejj@github.com
description: > # this means to ignore newlines until "baseurl:"
  Product Manager at GitHub passionate about leveraging technology
  to improve the world.  

# social links
twitter_username: boyle.james.j # DO NOT include the @ character, or else the build will fail!
github_username:  boylejj # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
