title: Product Management by Jim
author: Jim Boyle
email: boyle.james.j@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Product Management professional poassionate about leveraging technology
  to improve the world. 

# social links
twitter_username: boyle.james.j # DO NOT include the @ character, or else the build will fail!
github_username:  boylejj # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
